# -*- coding: utf-8 -*-
""".ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/Egor1c/caa17f811eedc67ddd0d646a7095ac90/.ipynb
"""

pip install gigachat

pip install gigachain

pip install aiogram

pip install telebot

from tensorflow.keras.applications import EfficientNetB0
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.efficientnet import preprocess_input
from tensorflow.keras.applications.efficientnet import decode_predictions
import numpy as np

import telebot
import io

from PIL import Image
import __main__ as main

from langchain.schema import HumanMessage, SystemMessage
from langchain.chat_models.gigachat import GigaChat

# Авторизация в сервисе GigaChat
chat = GigaChat(credentials='Y2M0NDczY2QtNmQ5YS00NjU4LWJjNjUtYjFlMzc4NmE2YWM2OjU0MDc1YzAzLWUxZWQtNGE1Ni05OTEwLTVmZTRhM2UzOTdjYw==', verify_ssl_certs=False)

messages = [
    SystemMessage(
        content="Тебя зовут Егор и ты помогаешь людям выявить их плюс."
    )
]

while(True):
    # Ввод пользователя
    user_input = input("User: ")
    messages.append(HumanMessage(content=user_input))
    res = chat(messages)
    messages.append(res)
    # Ответ модели
    print("Bot: ", res.content)

from langchain.schema import HumanMessage, SystemMessage
from langchain.chat_models.gigachat import GigaChat
import telebot
from telebot import types
chat = GigaChat(credentials='Y2M0NDczY2QtNmQ5YS00NjU4LWJjNjUtYjFlMzc4NmE2YWM2OjU0MDc1YzAzLWUxZWQtNGE1Ni05OTEwLTVmZTRhM2UzOTdjYw==', verify_ssl_certs=False)
# Авторизация в сервисе GigaChat
chat = GigaChat(credentials='Y2M0NDczY2QtNmQ5YS00NjU4LWJjNjUtYjFlMzc4NmE2YWM2OjU0MDc1YzAzLWUxZWQtNGE1Ni05OTEwLTVmZTRhM2UzOTdjYw==', verify_ssl_certs=False)

messages = [
    SystemMessage(
        content="Тебя зовут Егор и ты помогаешь людям выявить их плюс."
    )
]

token = '6853714269:AAEZZ8RIEBTj32tUIMotgjjWFXaVQlHwwTc'
bot = telebot.TeleBot(token)


@bot.message_handler(func = lambda _ :True)
def handle_message(message):
# Ввод пользователя
    user_input = message.text
    messages.append(HumanMessage(content=user_input))
    res = chat(messages)
    messages.append(res)
    # Ответ модели
    print("Bot: ", res.content)
    bot.send_message(chat_id=message.from_user.id,text=res.content)

bot.polling()
